#page title
page_title                                : TeloTel                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
#ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

#appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=ir.alphasoft.mrgram                                          # Enter Google Play Store URL.
presskit_download_link                    :                                      # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ic_lan.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Telotel                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Fast and Free for ever.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Emil Baehr                                
your_link                                 :                  
your_city                                 : Copenhagen                                
email_address                             : takxxm@gmail.com
facebook_username                         :                                           
instagram_username                        : telotelorg
twitter_username                          : telotelorg
github_username                           : telotelorg
youtube_username                          : telotelorg



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Anti Filter
    description                           : Always connect via internal proxy and Tor network
    fontawesome_icon_name                 : plug
    
  - title                                 : ghost state
    description                           : See other people s messages overnight
    fontawesome_icon_name                 : user-secret

  - title                                 : Anti-advertising
    description                           : Ads in the app are closed for your convenience.
    fontawesome_icon_name                 : window-close

  - title                                 : Pro Forward
    description                           : Send simple and easy messages to your friends to groups and ...
    fontawesome_icon_name                 : forward

  - title                                 : Profile Maker
    description                           : Beautify your profile with various tools
    fontawesome_icon_name                 : user
  
  - title                                 : FindUser
    description                           : Find your friends quickly and easily
    fontawesome_icon_name                 : search

  - title                                 : online Contact
    description                           : Be aware of your friends being online
    fontawesome_icon_name                 : users

  - title                                 : Advanced setting 
    description                           : Enable advanced settings for yourself and enjoy
    fontawesome_icon_name                 : wrench

  - title                                 : Message Detail
    description                           : Get the details of the message with one click
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
